### ISSUE TITLE
Fields look broken on Payload 2.0

### ISSUE THREAD

**Issue by tyteen4a03** [NouanceLabs/payload-better-fields-plugin#27]
I have a field setup like this in my collection:

```
        ...TelephoneField(
            {
                name: "contactPhoneNumber",
                label: "Default Contact Person Phone Number",
                admin: {
                    placeholder: "+44 300 636 1967",
                },
            },
            {
                defaultCountry: "gb",
            },
        ),
        ```

In Payload 2.0 it looks like this:

![Screenshot 2023-10-13 at 13 54 33](https://github.com/NouanceLabs/payload-better-fields-plugin/assets/440015/e6fbde67-07cc-406d-a151-6e9a9f3ff104)

**Comment by paulpopus** [comment]
Hey, will take a look at this issue this week!

**Comment by tyteen4a03** [comment]
I found the issue - I think I somehow duplicated the fields. Sorry for the false alarm!
