### ISSUE TITLE
Slugification of special characters for scandinavian languages

### ISSUE THREAD

**Issue by Augigauki** [NouanceLabs/payload-better-fields-plugin#46]
The character `æ` correctly converts to `ae`, but characters `ø` and `å` incorrectly converts to `o` and `a`. They should instead convert to `oe` (ø/ö) and `aa` (å) respectively.

In swedish ä = æ, so `ä` should convert to `ae` as well.

**Comment by paulpopus** [comment]
Before I look into a solution on my end, can you test passing the locale into your `slugify` config?

Something like this:

```ts
//...
slugify: { lower: true, remove: /[*+~.()'"!?#\.,:@]/g, locale: 'sv' }
//...
```

The full list of locale specific transliterations are here https://github.com/simov/slugify/blob/master/config/locales.json

We use https://www.npmjs.com/package/slugify under the hood as outlined under the Options for https://github.com/NouanceLabs/payload-better-fields-plugin#slug-field
