### ISSUE TITLE
Field wrapper missing `field-type` class, causes gap breakages

### ISSUE THREAD

**Issue by tyteen4a03** [NouanceLabs/payload-better-fields-plugin#47]
The field wrapper for the telephone field (and I suspect other fields in this plugin too) is missing the `field-type` class, which causes the spacing between the field and other built-in fields to be incorrect. See screenshot:

![image](https://github.com/NouanceLabs/payload-better-fields-plugin/assets/440015/48b34779-de42-409c-9c33-f067ec17874e)

**Comment by paulpopus** [comment]
Added the field-type to the main wrapper as well, fixed as of 1.2, will figure out a better solution for consistency
