### ISSUE TITLE
Incorrect example Number field

### ISSUE THREAD

**Issue by Evanion** [NouanceLabs/payload-better-fields-plugin#53]
The example for the `NumberField` seems to be incorrect, the correct structure that worked for me, was:
```ts
...NumberField(
  {
    name: "yield",
    label: "Yield",
    required: true,
  },
  {
    suffix: "%",
    decimalScale: 0,
    fixedDecimalScale: true,
  }
),
```
version: ^1.1.1

**Comment by paulpopus** [comment]
Thanks for reporting this, forgot to update the readme in the 1.0 update. Fixed now!
