### ISSUE TITLE
SlugField: checkbox enabled boolean doesn't work

### ISSUE THREAD

**Issue by damnsamn** [NouanceLabs/payload-better-fields-plugin#63]
Setting `enabled: false` results in the checkbox still rendering and functioning as if it were `true`, seems to have no impact.

Config:
<img width="208" alt="image" src="https://github.com/NouanceLabs/payload-better-fields-plugin/assets/17864782/f6259074-66ae-4c13-84a1-f8b53c55a973">

UI:
<img width="307" alt="image" src="https://github.com/NouanceLabs/payload-better-fields-plugin/assets/17864782/63622dd2-4429-4929-a3a0-621262167352">

**Comment by paulpopus** [comment]
Thanks for the report, will look into this!

**Comment by paulpopus** [comment]
Hey, this should be fixed in the newest release!

**Comment by damnsamn** [comment]
You legend! Thanks ☺️
________________________________
