### ISSUE TITLE
Custom slugify.remove value not applied

### ISSUE THREAD

**Issue by slavanossar** [NouanceLabs/payload-better-fields-plugin#69]
When defining a custom `remove` value, the value is lost when [the custom `slugify` config is merged with the default](https://github.com/NouanceLabs/payload-better-fields-plugin/blob/bbeba77de82c347205098d9a75f0d148630cd6e8/src/fields/Slug/index.ts#L79-L85).

![image](https://github.com/NouanceLabs/payload-better-fields-plugin/assets/7077600/a1d72596-ea55-4849-bf9c-1002a78b54a2)

`slugify.remove` ends up being an empty object after the `deepMerge`.

```js
SlugField(
  {
    name: 'slug',
    admin: { position: 'sidebar' },
  },
  {
    useFields: ['clientName'],
    slugify: { remove: /[*+~.()'"\/!?#\.,:@]/g },
  },
)
```

**Comment by slavanossar** [comment]
Would probably be good to update the default to include `/` characters, which is why I was trying to add a custom regex.

**Comment by paulpopus** [comment]
Hey thanks for the bug report. Pushed a fix now which fixes this config problem and I added \ and / to the default regex
