### ISSUE TITLE
localized labels not working

### ISSUE THREAD

**Issue by carstenblt** [NouanceLabs/payload-better-fields-plugin#72]
When I am using a SlugField like

```
...SlugField(
      {
        name: "slug",
        label: {
          en: "Path",
          de: "Pfad",
        },
      },
      {
        useFields: ["title"],
      },
    ),
```
the label is not shown correctly. It just shows "S" as the label. Using

```
label: "Path"
```

works correctly.

**Comment by paulpopus** [comment]
Hey I just cut a fix particularly for this, there's a bigger issue with the deepMerge utility for me to look at down the line but for now this should work
